version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    ports:
      - '5432:5432'
    volumes:
      - path:/var/lib/postgres/data

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "8081:8081"
      - "9010:9010"
    depends_on:
      - db

volumes:
  path:
    driver: local
