version: '3.8'
services:
  db:
    container_name: db
    build:
      context: ./database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    ports:
      - '5432:5432'
    volumes:
      - path:/var/lib/postgres/data

  backend:
    container_name: backend
    build:
      context: .
    expose:
      - 8081
    ports:
      - "8081:8081"
      - "9010:9010"
    depends_on:
      - db
    environment:
      JVM_OPTS: >
        -Dcom.sun.management.jmxremote.rmi.port=9010
        -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.port=9010
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.local.only=false
        -Djava.rmi.server.hostname=localhost

#  hyperfoil:
#    container_name: hyperfoil
#    image: quay.io/hyperfoil/hyperfoil
#    ports:
#      - "8080:8083"

volumes:
  path:
    driver: local
