CREATE TABLE app_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uc_user_email UNIQUE (email),
    CONSTRAINT uc_user_username UNIQUE (username)
);


CREATE TABLE category_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_category_type PRIMARY KEY (id)
);

CREATE TABLE condition_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_condition_type PRIMARY KEY (id)
);

CREATE TABLE offer_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),

    CONSTRAINT pk_offer_type PRIMARY KEY (id)
);

CREATE TABLE product
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    price             DOUBLE PRECISION                        NOT NULL,
    description       VARCHAR(255)                            NOT NULL,
    rating            DOUBLE PRECISION                        NOT NULL,
    user_id           BIGINT,
    category_type_id  BIGINT,
    condition_type_id BIGINT,
    offer_type_id     BIGINT,

    CONSTRAINT pk_product PRIMARY KEY (id),
    CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_type_id) REFERENCES category_type (id),
    CONSTRAINT FK_PRODUCT_ON_CONDITION FOREIGN KEY (condition_type_id) REFERENCES condition_type (id),
    CONSTRAINT FK_PRODUCT_ON_OFFER_TYPE FOREIGN KEY (offer_type_id) REFERENCES offer_type (id),
    CONSTRAINT FK_PRODUCT_ON_USER FOREIGN KEY (user_id) REFERENCES app_user (id)
);
